version: '2'

networks:
  plankanet:
    driver: bridge

services:
  postgresql:
    image: dimaskiddo/debian-buster:postgresql-12
    networks:
      - plankanet
    env_file: ./env/postgresql.env
    volumes:
      - ./data/postgresql:/var/lib/pgsql/data
    restart: unless-stopped

  planka:
    image: meltyshev/planka:latest
    command: >
      node app.js --prod
    networks:
      - plankanet
    ports:
      - 80:1337
    env_file: ./env/planka.env
    volumes:
      - ./data/planka/user-avatars:/app/public/user-avatars
      - ./data/planka/project-background-images:/app/public/project-background-images
      - ./data/planka/attachments:/app/public/attachments
    restart: unless-stopped
    depends_on:
      - postgresql
